apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL database with support for local and cloud deployments
type: application
version: 0.1.1
appVersion: "16"
keywords:
  - postgresql
  - database
  - sql
home: https://github.com/leverages/helm
icon: https://www.postgresql.org/media/img/about/press/elephant.png
sources:
  - https://github.com/leverages/helm/tree/main/charts/postgresql
  - https://github.com/postgres/postgres
maintainers:
  - name: Leverages
    url: https://github.com/leverages
