# Default values for postgresql chart
# This is a YAML-formatted file.

# Deployment type: "local" or "cloud"
deploymentType: "local"

# PostgreSQL configuration
postgresql:
  # Official PostgreSQL Docker image
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  
  # Database credentials
  auth:
    # PostgreSQL super user
    username: postgres
    # Use existing secret or create new one
    existingSecret: ""
    # Password for PostgreSQL super user (ignored if existingSecret is provided)
    password: "changeme"
    # Name of database to create
    database: "postgres"

  # PostgreSQL configuration parameters
  config:
    # PostgreSQL port
    port: 5432
    # Max connections
    maxConnections: 100
    # Shared buffers
    sharedBuffers: "128MB"
    # Effective cache size
    effectiveCacheSize: "256MB"

# Local deployment configuration (StatefulSet)
local:
  # Number of replicas
  replicaCount: 1
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  # Storage configuration for local deployment
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
    accessMode: ReadWriteOnce

  # Service configuration for local deployment
  service:
    type: ClusterIP
    port: 5432

# Cloud deployment configuration (Deployment with PV/PVC)
cloud:
  # Number of replicas
  replicaCount: 1
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  # Persistent Volume configuration
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""
    accessMode: ReadWriteOnce
    # Persistent Volume configuration
    persistentVolume:
      enabled: true
      capacity: 20Gi
      accessMode: ReadWriteOnce
      storageClass: ""
      hostPath: ""  # For hostPath type PV
      
  # Service configuration for cloud deployment
  service:
    type: LoadBalancer
    port: 5432
    # LoadBalancer specific configuration
    loadBalancerIP: ""
    loadBalancerSourceRanges: []

# Security context
securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}